#!/usr/bin/env lua

-- Set Lua library paths.
-- based on findbin -- https://gist.github.com/1342365
-- and lib -- https://gist.github.com/1342319
local function findbin()
  local script = arg and arg[0] or ''
  local bin = script:gsub('[/\\]?[^/\\]+$', '') -- remove file name
  if bin == '' then bin = '.' end
  return bin
end
local bin = findbin()
package.path = package.path..';'..bin..'/lib/?.lua'

require 'luainspect.command'

